import { ERROR_CODES, HTTP_STATUS } from '@goalforge/shared';

export const HTTP_STATUS_MAP: Record<string, number> = {
  [ERROR_CODES.VALIDATION_ERROR]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.BAD_REQUEST]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.UNAUTHORIZED_ERROR]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.FORBIDDEN_ERROR]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.NOT_FOUND_ERROR]: HTTP_STATUS.NOT_FOUND,
  [ERROR_CODES.CONFLICT_ERROR]: HTTP_STATUS.CONFLICT,
  [ERROR_CODES.RATE_LIMITED_ERROR]: HTTP_STATUS.RATE_LIMITED,
  [ERROR_CODES.TIMEOUT_ERROR]: HTTP_STATUS.REQUEST_TIMEOUT,
  [ERROR_CODES.DATABASE_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: HTTP_STATUS.SERVICE_UNAVAILABLE,
  [ERROR_CODES.INTERNAL_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.UNKNOWN_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.CLERK_AUTH_ERROR]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.CLERK_FORBIDDEN_ERROR]: HTTP_STATUS.FORBIDDEN,
} as const;

export function getStatusCode(code: string): number {
  return HTTP_STATUS_MAP[code] ?? HTTP_STATUS.INTERNAL_SERVER_ERROR;
}
